### ISSUE TITLE
GPG Error

### ISSUE THREAD

**Issue by bitstarr** [soohwa/apt#1]
After apt-get update this message occures:

W: GPG-Error: https://soohwa.github.io/apt/debian wheezy InRelease: Die folgenden Signaturen waren ungültig: D32DFFE6FAAB9AC43C17D7B693349044FDEB78E7
W: The repository 'https://soohwa.github.io/apt/debian wheezy InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Debian current stable

**Comment by soohwa** [comment]
Hi ! I updated the [README.md](https://github.com/soohwa/apt/blob/master/README.md). So in order to import the gpg key you can do this:
```bash
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv FDEB78E7
```

But this package was not tested on systemd distributions (like the latest debian stable).

**Comment by soohwa** [comment]
I don't know why it succeeds with debian 7.x but fails with debian 9.x ... I'm investigating ...

**Comment by soohwa** [comment]
I updated the repository with sha256 signature instead of sha1. So you can now retry.

**Comment by soohwa** [comment]
But this package is not designed to work with a systemd operating system : it does not work with debian >= 8

**Comment by bitstarr** [comment]
with the new key it works without warnings. thanks!
